#!/bin/sh

alias v="nvim"
alias ll="ls -al --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias rm="rm -vI"
alias mv="mv -iv"
alias cp="cp -iv"
alias mkd="mkdir -pv"

# pacman
alias pas="sudo pacman -S"
alias par="sudo pacman -Rn"
alias pau="sudo pacman -Syu"

alias upd="yay -Syyu"

# git
alias g="git"
alias gb="git branch"
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gps="git push"
alias gpl="git pull"
alias gcm="git checkout main"
alias gcl="git clone"

# other
alias e="$EDITOR"
alias v="$EDITOR"
alias b="$BROWSER"

# directories
alias sd="$HOME/.local/bin"
alias sds="$HOME/.local/bin/status"
alias im="$HOME/Pictures"
alias dl="$HOME/Downloads"
alias cfg="cd $XDG_CONFIG_HOME"
