#!/bin/sh

xcompmgr &
dunst &
unclutter &
xrandr --dpi 96 &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$! &
setbg &
pipewire &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"